#!/usr/bin/env python3
"""
Build the portfolio site from the design system.

    python3 build_site.py

The design system stays the single source of truth for how anything looks or
behaves. This script lifts the three shared assets out of design-system.html
so the site never carries its own drifting copy:

    site/assets/fonts.css   @font-face, base64 woff2, no network
    site/assets/site.css    the stylesheet
    site/assets/site.js     the runtime (reveal, nav, sticker field)

Page markup is authored by hand under site/ — a real page is not a specimen,
and the two should be allowed to differ. What must never differ is the system
underneath them, which is why the assets are generated and the pages are not.

It also writes a self-contained copy of each page to site/dist/, with the
assets inlined, for publishing somewhere that cannot serve a folder.
"""
import re, os, pathlib

ROOT = pathlib.Path(__file__).parent
SITE = ROOT / "site"
ASSETS = SITE / "assets"
DIST = SITE / "dist"
ARTIFACT = DIST / "artifact"

doc = (ROOT / "design-system.html").read_text()
head = doc[doc.index("<head>") + 6: doc.index("</head>")]

styles = re.findall(r"<style>(.*?)</style>", head, re.S)
assert len(styles) == 2, f"expected 2 <style> blocks in the design system, found {len(styles)}"
fonts, css = styles

script = re.search(r"<script>\n(\(function\(\)\{.*?)\n</script>", doc, re.S)
assert script, "could not find the runtime <script> in the design system"
js = script.group(1)

# The runtime must survive a page that has no deletion-test button, no
# component demos and no swatch grid. Everything it touches is either queried
# by class (zero matches is fine) or null-guarded at the source.
assert "if (dt) dt.addEventListener" in js, \
    "the deletion-test wiring is not null-guarded — it will throw on the site"

BANNER = ("/* Generated by build_site.py from design-system.html.\n"
          "   Edit the design system, then rebuild — changes here are overwritten. */\n")

ASSETS.mkdir(parents=True, exist_ok=True)
(ASSETS / "fonts.css").write_text(BANNER + fonts)
(ASSETS / "site.css").write_text(BANNER + '@import url("./fonts.css");\n' + css)
(ASSETS / "site.js").write_text(
    "// Generated by build_site.py from design-system.html.\n"
    "// Edit the design system, then rebuild — changes here are overwritten.\n" + js)

# --- self-contained copies -------------------------------------------------
# A published page cannot fetch a sibling folder, so dist/ carries everything
# inline. Same markup, same order, only the delivery differs.
pages = sorted(p for p in SITE.glob("*.html"))
assert pages, "no pages in site/ to build"
DIST.mkdir(parents=True, exist_ok=True)
ARTIFACT.mkdir(parents=True, exist_ok=True)
for page in pages:
    html = page.read_text()
    assert '<link rel="stylesheet" href="./assets/site.css">' in html, \
        f"{page.name} does not link the generated stylesheet"
    html = html.replace(
        '<link rel="stylesheet" href="./assets/site.css">',
        "<style>" + fonts + "</style>\n<style>" + css + "</style>")
    html = html.replace(
        '<script src="./assets/site.js"></script>',
        "<script>\n" + js + "\n</script>")
    assert "./assets/" not in html, f"{page.name} still references ./assets/ after inlining"
    (DIST / page.name).write_text(html)

    # ...and an artifact copy, for hosts that supply their own <head>. Same
    # page with the document skeleton stripped, plus a pinned white ground:
    # the site is light-mode only and the viewer's theme must not show through.
    body = html[html.index("<body>") + 6: html.rindex("</body>")]
    (ARTIFACT / page.name).write_text(
        "<style>\n/* Light-mode only by design. Pin the ground so a dark viewer\n"
        "   theme cannot show through behind the page. */\n"
        'html, :root[data-theme="dark"], :root[data-theme="light"]{\n'
        "  background:#FFFFFF; color-scheme:light;\n}\n</style>\n"
        "<style>" + fonts + "</style>\n<style>" + css + "</style>\n" + body)

for f in ["site/assets/fonts.css", "site/assets/site.css", "site/assets/site.js"] + \
         [f"site/{p.name}" for p in pages] + [f"site/dist/{p.name}" for p in pages] + \
         [f"site/dist/artifact/{p.name}" for p in pages]:
    print(f"  {f:30} {os.path.getsize(ROOT / f) // 1024:>5} KB")
print("built.")
