#!/usr/bin/env python3
"""
Regenerate every derived file from design-system.html, which is the only
source of truth. Run after editing it:

    python3 build.py

Writes:
  src/index.html          markup only
  src/design-system.css   stylesheet, fonts referenced not inlined
  src/tokens.css          the custom properties on their own
  dist/artifact.html      publish copy, document skeleton stripped

Nothing here is clever, but two things are easy to get wrong by hand:

1. Only column-zero `:root{` blocks are token blocks. There are also
   `:root{}` blocks nested inside @media queries that override --margin
   and --gutter; pulling those into tokens.css silently removes the
   responsive margins AND swallows every rule up to the next closing
   brace, which knocks out the whole type scale.
2. The publish wrapper supplies its own <head>, so the artifact copy must
   not carry one, and needs the ground pinned to white because the system
   is light-mode only and the viewer's theme must not show through.
"""
import re, os, pathlib

ROOT = pathlib.Path(__file__).parent
SRC = ROOT / "design-system.html"
doc = SRC.read_text()

head = doc[doc.index("<head>") + 6: doc.index("</head>")]
body = doc[doc.index("<body>") + 6: doc.index("</body>")]

styles = re.findall(r"<style>(.*?)</style>", head, re.S)
assert len(styles) == 2, f"expected 2 <style> blocks, found {len(styles)}"
fonts, main = styles

# --- tokens: column-zero :root blocks only (see note 1 above) ---------------
roots = re.findall(r"(?m)^:root\{.*?^\}", main, re.S)
assert len(roots) >= 3, f"expected >=3 token blocks, found {len(roots)}"
for r in roots:
    assert "@media" not in r, "matched a nested :root — would break responsive margins"
    main = main.replace(r, "", 1)
main = re.sub(r"\n{3,}", "\n\n", main)

# guard against the failure mode that motivated this script
for must in (".t-hero{", ".t-display{", ".t-h1{", "max-width:1024px", "max-width:640px"):
    assert must in main, f"stylesheet lost {must!r} during the split"

(ROOT / "src").mkdir(exist_ok=True)
(ROOT / "src" / "tokens.css").write_text(
    "/* ==========================================================================\n"
    "   Wendy Wong — Design System v1.0 · design tokens\n"
    "   Generated by build.py — edit design-system.html, not this file.\n"
    "   ========================================================================== */\n\n"
    + "\n\n".join(roots) + "\n")

(ROOT / "src" / "design-system.css").write_text(
    "/* ==========================================================================\n"
    "   Wendy Wong — Design System v1.0 · stylesheet\n"
    "   Generated by build.py — edit design-system.html, not this file.\n"
    "   Readable copy: fonts are referenced, not inlined. The offline build is\n"
    "   ../design-system.html.\n"
    "   ========================================================================== */\n"
    '@import url("./tokens.css");\n'
    '@import url("https://fonts.googleapis.com/css2?family=Figtree:ital,wght@0,300..700;'
    '1,300..500&family=Caveat:wght@400..700&display=swap");\n' + main)

(ROOT / "src" / "index.html").write_text(
    '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
    '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
    "<title>wendy wong — design system v1.0 — clinical field notebook</title>\n"
    '<link rel="stylesheet" href="./design-system.css">\n</head>\n<body>'
    + body + "</body>\n</html>\n")

# --- artifact copy (see note 2 above) --------------------------------------
pin = ('<style>\n'
       '/* Light-mode only by requirement (see §00). Pin the ground so the\n'
       "   viewer's dark theme cannot show through behind the page. */\n"
       'html, :root[data-theme="dark"], :root[data-theme="light"]{\n'
       '  background:#FFFFFF; color-scheme:light;\n}\n</style>')
(ROOT / "dist").mkdir(exist_ok=True)
(ROOT / "dist" / "artifact.html").write_text(
    pin + "\n<style>" + fonts + "</style>\n<style>" + main + "</style>\n" + body)

for f in ("src/index.html", "src/design-system.css", "src/tokens.css", "dist/artifact.html"):
    print(f"  {f:26} {os.path.getsize(ROOT / f) // 1024:>4} KB")
print("built.")
